### ISSUE TITLE
[功能请求] 希望加入收藏多选后下载，以及下载限速功能

### ISSUE THREAD

**Issue by jinkeloid** [lanyeeee/picacomic-downloader#10]
### 原因

收藏有许多本漫画想都下载下来，同时希望不给服务器带来太大负担（怕被封号）

### 功能简述

1、收藏页下载功能添加复选框，或者指定收藏夹页数进行下载；
2、支持配置下载限速/下载单本漫画后冷却时间

### 功能逻辑

1、批量下载功能：将选择的漫画加入列表，按顺序进行下载
2、下载限速功能：下载完一本漫画后，等待设定的时间再下载下一本

**Comment by lanyeeee** [comment]
已在[v0.3](https://github.com/lanyeeee/picacomic-downloader/releases/tag/v0.3)完成
没有做多选，而是做成了一键下载按钮
下载整页没有做，因为感觉会给哔咔那边带来压力，如果需要请另开issue讨论
限速功能做成了每个章节下载完成后休息x秒
