### ISSUE TITLE
[功能请求] 下载附加作者名？

### ISSUE THREAD

**Issue by Smile8848** [lanyeeee/picacomic-downloader#17]
### 原因

但本子名感觉不完整，也有记录的习惯。

### 功能简述

作者：Finecraft69 (6ro-)
本子名：(C92) 悦チウ人 (DISCIPLINE)
下载出来是\[Finecraft69 (6ro-)] (C92) 悦チウ人 (DISCIPLINE) 
这种形式

### 功能逻辑

可选设置？

### 实现参考

无

**Comment by lanyeeee** [comment]
已在[v0.4](https://github.com/lanyeeee/picacomic-downloader/releases/tag/v0.4)实现
