### ISSUE TITLE
[Bug] 闪退崩溃

### ISSUE THREAD

**Issue by wuwuyi551** [lanyeeee/picacomic-downloader#25]
### 问题描述

在点击（一键下载全部章节）后，出现  等待中 下载XXX 时出现较多次数的崩溃闪退，特别是一次下载多个章节或者单一章节文件数较多（5个以上）时

### 预期行为

下载较大文件或者一次下载较多文件也不崩溃闪退

### 实际行为

闪退

### 工具版本号

v0.4

### 其他

暂时无法确定是否为梯子网络不稳定导致，有时解析成功后下载往往能够完成，没有中途闪退的情况

**Comment by lanyeeee** [comment]
这个问题我无法复现，只能根据你的描述尝试修复了
你试试 [v0.5.0](https://github.com/lanyeeee/picacomic-downloader/releases/tag/v0.5.0) 还会闪退崩溃么

**Comment by wuwuyi551** [comment]
> 这个问题我无法复现，只能根据你的描述尝试修复了 你试试 [v0.5.0](https://github.com/lanyeeee/picacomic-downloader/releases/tag/v0.5.0) 还会闪退崩溃么


0.5版本无闪退问题
