### ISSUE TITLE
[功能请求] 希望增加取消单个任务的功能

### ISSUE THREAD

**Issue by wuwuyi551** [lanyeeee/picacomic-downloader#26]
### 原因

有些漫画存在多个汉化组版本内容，一次下载全部章节会下载到重复内容，可以考虑增加任务取消功能

### 功能简述

在任务开始后能进行中止或暂停

### 功能逻辑

考虑在进度条一侧添加功能按钮

**Comment by lanyeeee** [comment]
你应该进入章节详情页面自行勾选要下载的章节(版本)，而不是在外面点一键下载然后取消不想要的章节

**Comment by wuwuyi551** [comment]
ok
