### ISSUE TITLE
[功能请求] 更换下载目录

### ISSUE THREAD

**Issue by ChangqingQ11** [lanyeeee/picacomic-downloader#5]
### 原因

现在默认的下载位置是C盘，下载完漫画后还需要费力剪切，希望能加入自定义下载目录的功能

### 功能简述

同上

### 功能逻辑

同上

**Comment by lanyeeee** [comment]
已在 [v0.2](https://github.com/lanyeeee/picacomic-downloader/releases/tag/v0.2) 完成
